train: dataset/train/images
val: dataset/valid/images
test: dataset/test/images

nc: 1
names: ['head']

roboflow:
  workspace: joseph-nelson
  project: hard-hat-workers
  version: 14
  license: Public Domain
  url: https://universe.roboflow.com/joseph-nelson/hard-hat-workers/dataset/14